### ISSUE TITLE
Non-optimal default additional bytes factor?

### ISSUE THREAD

**Issue by ersinakinci** [viascom/nanoid-postgres#14]
Question about the default additional bytes factor: why is it set to 1.6?

When I follow the instructions to [calculate the additional bytes factor](https://github.com/viascom/nanoid-postgres?tab=readme-ov-file#calculating-the-additional-bytes-factor-for-a-custom-alphabet) and pass the default alphabet (`_-0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`) I get 1.02 as a result. So shouldn't the default factor be 1.02 instead of 1.6?

For context, I'm trying to set a custom alphabet that consists of the default without any special characters (no `-` or `_`). I got 1.02 as a result, which seemed low, so I ran it with the default alphabet for comparison and got the same number, which made me wonder whether I was doing something wrong.

I don't know anything about the underlying Nano ID math or cryptology, I'm just a monkey punching keys.

Thanks so much for your work!

**Comment by nik-sta** [comment]
Hi @ersinakinci :) Thx for reaching out!

The 1.6 factor in the nanoid library's `customRandom()` function is based on empirical benchmarks rather than a strict mathematical calculation. It optimises performance by reducing the number of system calls needed to generate random bytes, ensuring enough valid bytes are obtained even after discarding those that exceed the alphabet size. This provides a good balance between efficiency and reliability across various scenarios. For more details, refer to [the original code on GitHub](https://github.com/ai/nanoid/blob/383cf87652963d3ae881bfe9afef30e31477827c/index.js#L33).

The formula we provided to calculate the additional bytes factor for a custom alphabet in the `nanoid()` function is designed to optimise performance by balancing byte generation and discard rates. It computes a bitmask based on the alphabet size, normalises the difference between this bitmask and the alphabet length, and adds a baseline factor of 1. This ensures enough valid bytes are generated in each batch, minimising the need for repeated system calls to the random number generator. While the default 1.6 factor in nanoid is empirically derived and works well across many scenarios, the custom-calculated factor offers a more tailored optimisation for specific alphabet sizes. This customisation can enhance computational efficiency by reducing redundant operations, particularly when the default factor doesn't fit the custom alphabet's characteristics perfectly. It serves as a practical approach to enhance computational efficiency by reducing redundant operations, but empirical validation and potential adjustments may still be necessary for optimal performance.

The desired effect is to have less memory overhead.

It's perfectly normal to have questions, and there's no need to hesitate — everyone starts somewhere! If you're curious or need clarification, feel free to ask; we're all here to learn together and I'm no different from you.

**Comment by ersinakinci** [comment]
Oh interesting, it's empirically derived. That's neat!

Thanks for the in-depth explanation @nik-sta. So the formula you provide is basically a heuristic? Any advice on what the factor should roughly be if all I've done is remove the special chars? Maybe I should keep it at 1.6? I'd rather not go down the rabbit hole of empirical testing myself.

**Comment by nik-sta** [comment]
I'm doing the same and not touching the 1.6 factor. I have never had any issues running with those settings until today. But could it be more optimised and, therefore, use fewer bytes? I would assume yes.
